apiVersion: v1
kind: Secret
metadata:
  name: {{ include "consenthub.fullname" . }}-secrets
  labels:
    {{- include "consenthub.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.backend.secrets.secretKey | quote }}
  JWT_SECRET_KEY: {{ .Values.backend.secrets.jwtSecretKey | quote }}
  ADMIN_API_KEY: {{ .Values.backend.secrets.adminApiKey | quote }}
  DATABASE_URL: {{ include "consenthub.databaseUrl" . | quote }}
